AWSTemplateFormatVersion: '2010-09-09'
Description: ECS cluster

Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "application"
      EmptyOnDelete: true
      ImageTagMutability: MUTABLE